# This file is a template, and might need editing before it works on your project.
# Official Java image. Look for the different tagged releases at
# https://hub.docker.com/r/library/java/tags/ . A Java image is not required
# but an image with a JVM speeds up the build a bit.
before_script:
  # Enable the usage of sources over https
  - sudo apt-get update -yqq
  - sudo apt-get install apt-transport-https -yqq
  # Add keyserver for SBT
  - echo "deb http://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
  # Install SBT
  - sudo apt-get update -yqq
  - sudo apt-get install sbt -yqq
  # Log the sbt version
  - cd epsilonsecurity
  - echo MADE IT
  - sbt -Djline.terminal=jline.UnsupportedTerminal version
  - echo PRINTED VERSION

test:
  script:
    # Execute your project's tests
    - pwd
    - sbt -Djline.terminal=jline.UnsupportedTerminal clean test
